### ISSUE TITLE
flake: enterprise/wsproxy TestDERPOnly

### ISSUE THREAD

**Issue by mafredri** [coder/internal#114]
```
    t.go:93: 2024-01-26 10:57:56.019 [erro]  net.workspace-proxy.servertailnet: reinit multi agent ...
        error= dial coordinate websocket:
                   github.com/coder/coder/v2/enterprise/wsproxy/wsproxysdk.(*Client).DialCoordinator
                       /home/runner/actions-runner/_work/coder/coder/enterprise/wsproxy/wsproxysdk/wsproxysdk.go:458
                 - failed to WebSocket dial: failed to send handshake request: Get "http://localhost:37847/api/v2/workspaceproxies/me/coordinate?version=2.0": context canceled
         *** slogtest: log detected at level ERROR; TEST FAILURE ***
```

https://github.com/coder/coder/actions/runs/7667128076/job/20896333269?pr=11825

**Comment by mtojek** [comment]
Spotted here: https://github.com/coder/coder/actions/runs/11379023829/job/31655767933

enterprise/wsproxy TestWorkspaceProxyWorkspaceApps_BlockDirect/WorkspaceAppsProxySubdomain/WildcardPortOK

Should we ignore coordinator re-init issues?

**Comment by spikecurtis** [comment]
It's a legit error --- we'd want to know if the workspace proxy can't connect to the Coordinator.

I think this is an issue of shutdown ordering.  You want the workspace proxy to shut down before you start tearing down Coderd. We do shut it down first, but don't wait until the servertailnet's background work goroutines actually finish, which can occasionally race with the Coordinator being shut down.
