### ISSUE TITLE
Port /modules page code to registry-v2

### ISSUE THREAD

**Issue by bcpeinhardt** [coder/internal#123]
Port the /modules page code from registry.coder.com over to registry-v2.

**Comment by Kira-Pilot** [comment]
s

**Comment by bcpeinhardt** [comment]
There are gonna be two pieces to these page migration tickets: transitioning from the nextjs code that fetches content from github to having the go build process fetch the information (from git if possible but GitHub if necessary), and then refactoring the React code to use the generated assets.
I'm gonna start by seeing if I can do the first half, so that Michael isn't blocked on needing those assets.

**Comment by bcpeinhardt** [comment]
I've done the back end portion of this, at least the main content. Handing it off to @Parkreiner for now (we met and went over how it all worked).

**Comment by bcpeinhardt** [comment]
The terraform and markdown parsing side of this got moved to the backend. The terraform bit is done, the markdown bit is in progress.
On the frontend, Michael has the page pretty much done up, just needs some styling tweaks and will need to be updated to use the real download count and test run statuses when they're provided.
