### ISSUE TITLE
Port landing page code from registry.coder.com to registry-v2

### ISSUE THREAD

**Issue by bcpeinhardt** [coder/internal#124]
Port landing page code from registry.coder.com to registry-v2.

**Comment by Kira-Pilot** [comment]
xs

**Comment by buenos-nachos** [comment]
Increasing the scope for this one to be a full day, but I don't think I'll need more time than that.

I'm basically treating this part as the cherry on top, so it'll get tackled last. The only reason why I'm being more conservative with the estimates is that I've already had to rewrite a good chunk of the React code already for other pages, so I'm expecting that this won't be a straight port job

**Comment by buenos-nachos** [comment]
This is more or less done. There are technically a few extra features that we need to add to have full parity (sorting items by download count, listing the download counts), but that hinges on some backend updates

I think that if push comes to shove, we can put this out as-is, but hoping to close the gap on everything else by the end of the sprint.

**Comment by buenos-nachos** [comment]
Now that #235 is created, I'm going to go ahead and close out this issue. The current landing page is perfectly functional, so even if it doesn't have 100% parity yet, I don't think there's enough here to warrant keeping two tickets open
