### ISSUE TITLE
Port /module/[slug] code from registry.coder.com to registry-v2

### ISSUE THREAD

**Issue by bcpeinhardt** [coder/internal#125]
Port /module/[slug] code from registry.coder.com to registry-v2.

**Comment by Kira-Pilot** [comment]
m

**Comment by bcpeinhardt** [comment]
The backend work I was doing on /modules applies here too, so pulling this into in progress as well.

**Comment by matifali** [comment]
The tabs I want to see on `/modules/[slug]` pages are:
1. README.md --> renamed to docs/documentation
2. Variables --> Renamed to Inputs
3. Outputs --> [NEW]
4. Parameters
5. Apps
6. Source --> [REMOVE] and link to GitHub 

Additionally, download count.

[![Image](https://github.com/user-attachments/assets/a4729c41-7416-4906-a6a9-0a6d9ed3c13e)](https://www.figma.com/design/j1geLGOj2tb70Orw9l4jrq/Registry-v2?node-id=0-1&node-type=canvas&t=B6N3Wv10J40pv36P-0)

What do you think @chrifro and @bpmct?

**Comment by bcpeinhardt** [comment]
@matifali These issues (on the registry stability milestone) are specifically for describing porting existing functionality. Would you mind breaking this into it's own issue?

**Comment by matifali** [comment]
@bcpeinhardt. I extracted in #190

**Comment by buenos-nachos** [comment]
This is +90% done. Two more things to do:
1. Add download count once we can start making that available
2. Render out a parameters tab once the backend JSON payloads have been updated to include that information

**Comment by bcpeinhardt** [comment]
Parameters tab is done and download count has it's own issue now, so going to close this.
