### ISSUE TITLE
Port /templates code from registry.coder.com to registry-v2

### ISSUE THREAD

**Issue by bcpeinhardt** [coder/internal#126]
Port /templates code from registry.coder.com to registry-v2

**Comment by Kira-Pilot** [comment]
s

**Comment by matifali** [comment]
While we do this can we also use `coder/templates` as the source for templates?

**Comment by bcpeinhardt** [comment]
Is it kept in line with coder/coder/examples/templates?

The idea is to have feature parity with the existing registry and then pick up the proposed new feature work, but if the contents are kept in sync this is just a matter of swapping a url in the build script so I'm fine with it.

**Comment by matifali** [comment]
Yes. And we are soon adding CI to keep it in sync with coder/coder.

**Comment by bcpeinhardt** [comment]
The terraform and markdown parsing side of this got moved to the backend. The terraform bit is done, the markdown bit is in progress.
On the frontend, Michael has the page pretty much done up, just needs some styling tweaks and will need to be updated to use the real download count and test run statuses when they're provided.

**Comment by matifali** [comment]
While designing the download count. Can we do something similar to terraforn.registry.io? This helps measure popularity, too. 

<img src="https://github.com/user-attachments/assets/e0c9eeda-e149-422f-936b-31649255a973" width="300" alt="Download count over time">

Also, how are we planning to count a template download? The existing registry only offers only copy and paste.

We should add a button on the template page to download the template tar/zip with instructions on uploading it to Coder, i.e., `coder templates push <template name>`

Going forward, we also need to support importing templates from CLI and UI https://github.com/coder/coder/issues/15036, which should affect how we measure the download count.
