### ISSUE TITLE
Deploy registry-v2 on Cloud Run and setup and document blue/green deployment strategy

### ISSUE THREAD

**Issue by bcpeinhardt** [coder/internal#135]
Deploy registry-v2 on Cloud Run and setup and document blue/green deployment strategy

**Comment by Kira-Pilot** [comment]
m

**Comment by matifali** [comment]
Why did we choose Cloud Run? 
Is it more reliable than Vercel? 
What are the benefits? 
Can we preview PR deployments similar to Vercel to early preview contributions? (A more effortless local dev experience or a template on dev.coder.com could work, too, if we can't have PR deployments.)

**Comment by Kira-Pilot** [comment]
@matifali We decided on Cloud Run based on our history with it - there was a thread in the [RFC](https://www.notion.so/coderhq/registry-coder-com-Re-Architecture-120d579be59280058cc7e182f81d80f2?pvs=4#129d579be59280e98de2fac51d37e0bd) with more discussion.

We do seem to be encountering cache issues with Vercel.

Perhaps we can use Cloud Run's [revision tags](https://cloud.google.com/run/docs/managing/revisions) to preview contributions.

**Comment by bcpeinhardt** [comment]
@matifali @Kira-Pilot I know we haven't solved the vercel caching issue yet, but my instinct is it's related to the fact we're doing our own certificate handling. I'm thinking having something like dev.registry.coder.com may be a better way to ensure we can catch issues at the DNS level. What do you think?

**Comment by bcpeinhardt** [comment]
Done 😎
