### ISSUE TITLE
Write manual/runbook for operating registry-v2

### ISSUE THREAD

**Issue by bcpeinhardt** [coder/internal#136]
It would be ideal to have a complete manual for how to troubleshoot, report, and fix any issues. This would be like an incident playbook + an architecture map that would help an engineer with no context parachute in and fix an issue. The more automated scripts provided for performing maintenance actions the better.

I'm not exactly sure where this should live, but my gut instinct is as a collection of md files and scripts in the registry repo itself, so things stay centrally located. I don't really want to put it in Notion because 1. I want the manual in the same location as scripts to run during an incident and 2. I think company wiki's are not a good place for information that needs to be updated in parallel with source code.

We should however put a page in notion linking directly to the folder in the repo, in case someone goes looking for docs there during an incident.

I think the best way to test this will be to drop it in the lap of an engineer with no context and see how far they get deploying, debugging, and taking down an instance of the registry.

**Comment by Kira-Pilot** [comment]
s
