### ISSUE TITLE
Dogfood registry-v2

### ISSUE THREAD

**Issue by bcpeinhardt** [coder/internal#142]
Once we're satisfied with the state of the new registry, we should try to dogfood it before releasing it. We should also try to release it gradually.

The dogfooding can likely be done by configuring the templates we use internally at coder (specifically coder on coder) to point to registry-v2. This will help give us "real world usage" to detect any major issues before release. 
When we do release, we can do it as a gradual rollout. There are a couple strategies we could take for this, either at the level of domain registration or by highjacking registry.coder.com's service discovery endpoint to return the address of registry-v2. At the domain level would be ideal, so we could test the entire application.

**Comment by Kira-Pilot** [comment]
xs

**Comment by bcpeinhardt** [comment]
We did about 2.5 days of dogfooding with Coder on Coder. Things seemed to go fine, so I'm going to move this issue to complete.
