### ISSUE TITLE
Port components folder to new registry repo

### ISSUE THREAD

**Issue by Kira-Pilot** [coder/internal#143]
Port components folder to new registry repo

**Comment by Kira-Pilot** [comment]
s

**Comment by buenos-nachos** [comment]
Getting close to wrapping these up, but as I kept trying to adapt things, I ran into one problem or another that stopped me from plugging them right into the new project:
1. Some components were coupled directly to Next.js features
2. A lot of the components had really wonky HTML and/or CSS 
3. A lot of the code was non-idiomatic React, and state values weren't composed very well
4. A lot of the code wasn't wired up correctly, and just happened to work by coincidence. A lot of the input logic was a hair's breadth away from outright breaking
5. Even if some components were controlled/uncontrolled where appropriate, some had bugs that weren't previously caught (I've been cataloging problems with the old version of the codebase in a Notion doc)
6. It wasn't always clear why some parts of the code were chosen to be components, while others weren't

To be honest, I've basically rewritten every single component that's in the new codebase right now, largely from scratch. I still have a few more to make, but I'm almost done, and feel like I could wrap these up in about one more day

**Comment by buenos-nachos** [comment]
I think it's fair to say that all told, this was still Small-ish, in terms of total amount of time spent
It's just that it was harder to do all of this in one sitting, so I've been whittling away at it while working on everything else

**Comment by buenos-nachos** [comment]
I'm going to go ahead and mark this as done. I ended up basically tossing out the previous components folder entirely and rewrote a lot of it from scratch. There was just too much wonky React and CSS logic that it didn't feel responsible to copy over without any changes

This is all basically done now, though
