### ISSUE TITLE
vscode session 0 in prometheus metrics with new workspace activity

### ISSUE THREAD

**Issue by f0ssel** [coder/internal#144]
From the bug bash @stirby noted that he was seeing 0 session counts while using the latest version of the VSCode Extension. This may be from  us incorrectly aggregating this data in a query somewhere.

**Comment by f0ssel** [comment]
@stirby I'm not able to reproduce this locally, when I start a development server and connect with the "VS Code Desktop" button I'm seeing the correct prometheus metrics:

`coderd_agentstats_session_count_vscode{agent_name="main",username="admin",workspace_name="vscode1"} 1`

Do you know if you can reproduce this 0 value on your end?

**Comment by stirby** [comment]
Unable to reproduce.
