### ISSUE TITLE
vscode session 1 in deployment metrics with 2 users with new workspace activity

### ISSUE THREAD

**Issue by f0ssel** [coder/internal#145]
From the bug bash we found that when 2 different users connect with VSCode  was seeing 1/0/0/0 on deployment stats while using the latest version of the VSCode Extension. This may be from  us incorrectly aggregating this data in a query somewhere.

**Comment by f0ssel** [comment]
When connecting 2 different users using 2 vscode windows I'm seeing 2/0/0/0 like expected, so I'm not able to reproduce this. One thing I noticed is that if you open using the VSCode Desktop button on the workspace on 2 different workspaces without creating a new VSCode window it will just close the existing window and start a new one with the new connection - this may be what you were running into @stirby . I'd try making sure you have 2 windows open that are connected with different users to different workspaces to confirm the correct numbers.

**Comment by stirby** [comment]
Closing, I just logged out and logged in from the extension to the correct account to fix. User error sorry.
