### ISSUE TITLE
site: Add Breadcrumbs for admin settings pages

### ISSUE THREAD

**Issue by jaaydenh** [coder/internal#174]
- display breadcrumbs for deployment settings and organization settings pages
- For orgs, the final breadcrumb is the currently selected org

Figma:
https://www.figma.com/design/OR75XeUI0Z3ksqt1mHsNQw/Dashbord-v1?node-id=637-4129&t=0BTYhFaREJHyOlGu-1

**Comment by chrifro** [comment]
FYI, you can find the breadcrumb component [here](https://www.figma.com/design/WfqIgsTFXN2BscBSSyXWF8/Coder-kit?node-id=489-3467&t=BwQsMBrd2mgIgGbJ-1)
