### ISSUE TITLE
feat: deployment health notifications

### ISSUE THREAD

**Issue by dannykopping** [coder/internal#18]
Relates to https://github.com/coder/coder/issues/13328

Create notification_template instances for the following events, and enqueue notifications with those templates:

- [ ] access URL unhealthy
- [ ] database connection unhealthy
- [ ] DERP unhealthy
- [ ] provisioner daemons unhealthy
- [ ] websockets unhealthy
- [ ] wsproxy unhealthy

Admins should receives these notifications.

**Comment by stirby** [comment]
This makes more sense as a summary report. Weekly, admins would receive a report of any downtime on coder services in their deployment. I get these emails from services we use internally, and it's another place for less mature platform teams to check consistency in the coder service. 

@dannykopping makes a good point about us not becoming a high-frequency alerting system. Our notifications should be slow, async monitoring tools. What do you all think about converting this into a report?

**Comment by dannykopping** [comment]
(Asking legitimately here, not rhetorically): what do you perceive to be the value to operators about historical downtime over, say, the last week?

**Comment by stirby** [comment]
I see less mature organizations without an existing observability dashboard (perhaps in the early stages of rolling out Coder) wanting to ensure the platform's reliability. I don't think a report like this helps those who have used Coder for years, it would be more beneficial for measuring reliability in short intervals during the initial setup. 

It's simply another medium for triage. We could also only send the report if any failure has occurred. I'm also not pushing for this right now; I'm just adding more context for the future if customers request to be notified about what we display in the dashboard.

**Comment by dannykopping** [comment]
If this is a report, it'll only be retrospective; it won't help at all with triage.

In order to have this as a report, we'd need to capture the health metrics over time which would add more complexity than it's worth right now IMO. I think they're better off using the observability bundle.

I vote for closing this issue.
