### ISSUE TITLE
flake: e2e externalAuth

### ISSUE THREAD

**Issue by spikecurtis** [coder/internal#212]
```
==> Starting test external auth device
==> Finished test external auth device: failed
==> Starting test external auth web
==> Finished test external auth web: skipped
==> Starting test successful external auth from workspace
==> Finished test successful external auth from workspace: skipped
Data from pprof has been saved to test-results/debug-pprof-goroutine-external-auth-device.txt
  pw:api => selectors.setTestIdAttribute started +8ms
==> Output
  pw:api <= selectors.setTestIdAttribute succeeded +3ms
==> Errors
Error: listen EADDRINUSE: address already in use 0.0.0.0:50516
Data from pprof has been saved to test-results/debug-pprof-goroutine-successful-external-auth-from-workspace.txt
==> Output
Data from pprof has been saved to test-results/debug-pprof-goroutine-external-auth-web.txt
==> Output
[stderr] 
[stderr] 
[stderr] CSRF token not found
```

seen here: https://github.com/coder/coder/runs/32976358533

Looks like these use hardcoded ports, and so they flake if the port isn't available.

**Comment by mtojek** [comment]
I might be wrong but we enabled parallel e2e tests, right @matifali?

It could be a reason why these are failing. We can refactor them, but it could be harder than a simple port change (starting agent with Prometheus endpoint).

**Comment by matifali** [comment]
I think we do not run e2e tests in parallel., What I changed was only the runner type (moved from 16-core to a 4-core runner).

**Comment by dannykopping** [comment]
Provisionally closed by https://github.com/coder/coder/pull/15537

**Comment by johnstcn** [comment]
This cropped up again, opened https://github.com/coder/internal/issues/356 to track.
