### ISSUE TITLE
flake: TestServer/Logging/CreatesFile: TempDir RemoveAll cleanup fails

### ISSUE THREAD

**Issue by johnstcn** [coder/internal#213]
Seen here: https://github.com/coder/coder/actions/runs/11840487921/job/32994548981?pr=15518

```
    clitest.go:261: command "coder server" exited with error: <nil>
    testing.go:1231: TempDir RemoveAll cleanup: remove C:\Users\RUNNER~1\AppData\Local\Temp\TestServerLoggingCreatesFile3252984926\001\coder-logging-test-2246164782: The process cannot access the file because it is being used by another process.
```

**Comment by johnstcn** [comment]
Hey @defelmnq -- is it possible this is related to coder/coder#15438 ?

**Comment by spikecurtis** [comment]
Also seen on `main`: https://github.com/coder/coder/actions/runs/11836992728/job/32983079797

**Comment by ethanndickson** [comment]
Potentially caused by `t.Cleanup` from `TempDir` getting run before `clitest.Start`'s cleanup? Doesn't really explain why the flake only appeared after log rotation was added, however.

**Comment by spikecurtis** [comment]
I think there is a [known issue in Lumberjack](https://github.com/natefinch/lumberjack/pull/211) that there isn't a good way to ensure it is shut down and has closed all files.

**Comment by johnstcn** [comment]
Maybe can try wrapping it in the `lumberjackWriteCloseFixer` from `cli/agent.go`?

**Comment by ethanndickson** [comment]
I'm gonna give it a try
