### ISSUE TITLE
flake: `TestDeploymentInsights`

### ISSUE THREAD

**Issue by ethanndickson** [coder/internal#237]
Timed out on main, almost certainly a side-effect of running these tests with Postgres on Windows for the first time.
https://github.com/coder/coder/actions/runs/12174160664/job/33955697526

**Comment by spikecurtis** [comment]
another example:

https://github.com/coder/coder/actions/runs/12381754145/job/34561002563?pr=15899

@ethanndickson are you still working on this flake?

**Comment by ethanndickson** [comment]
This should be fixed when https://github.com/coder/coder/pull/15832 is merged
