### ISSUE TITLE
srecon: create sandbox demo environment

### ISSUE THREAD

**Issue by johnstcn** [coder/internal#31]
Create a sandboxed demo environment in a public cloud to demonstrate SRE-supporting capabilities of Coder:

- [ ] Create a small private Kubernetes cluster
- [ ] Install Coder via Helm / GitOps
- [ ] Install Coder observability chart
- [ ] Add templates created in https://github.com/coder/team-coconut/issues/29 and https://github.com/coder/team-coconut/issues/30

**Comment by dannykopping** [comment]
https://github.com/coder/srecon-emea-2024 implemented
