### ISSUE TITLE
Create a UI which visualizes workspace timings

### ISSUE THREAD

**Issue by dannykopping** [coder/internal#44]
Depends on https://github.com/coder/team-coconut/issues/43

![image](https://github.com/user-attachments/assets/d4cb5c84-75b4-4940-a263-6a0b0911aae5)
_from https://github.com/coder/coder/pull/14274_

**Comment by BrunoQuaresma** [comment]
Updated designs:

> We decided to go for a nested option as the previous version didn't work well the amount of short timeframe data

From @chrifro 

![image](https://github.com/user-attachments/assets/aa98928c-9560-444b-a100-100850fe911c)
![image](https://github.com/user-attachments/assets/de32410e-1d06-4a0d-8f11-eeec5c5cce9a)

**Comment by mtojek** [comment]
@BrunoQuaresma is it done now or is there anything left?

**Comment by BrunoQuaresma** [comment]
Closed by https://github.com/coder/coder/pull/15068
