### ISSUE TITLE
envbuilder: create video for release

### ISSUE THREAD

**Issue by johnstcn** [coder/internal#61]
Create video demonstrating Coder <-> Envbuilder integration in a template incl. caching + provider

This may be a post-release deliverable as we would want to showcase the 1.0.0 version as opposed to the RC version.

**Comment by bpmct** [comment]
Do we still want to do this? I'm leaning towards no

**Comment by johnstcn** [comment]
https://imgur.com/TzMcgvl


How does this look @bpmct ? The emojis are monochrome due to the tool I used to convert the asciinema .cast to a gif.

Here's the original asciinema cast: https://asciinema.org/a/Duce619BrWfs0yNVtv4vwKkQS

**Comment by bpmct** [comment]
Whoops, I missed this! The video looks great. We can link to link to it, or embed it on README.

**Comment by johnstcn** [comment]
Thanks Ben! I might try to make it a little smaller though as I forgot how big my monitor is 🙃
